os: osx

before_install:
  - brew install git-lfs
  - git-lfs install --system

script:
  - source setup.env && just test
  - just test int git_mirror
  # Currently failing for unknown reasons:
  # - just test int just_install_functions
