image:
- Visual Studio 2017
# - Windows Server 2016 # Doesn't work, private Beta I think
# - Visual Studio 2017 Preview # Doesn't have docker

environment:
  matrix:
  - MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  JUST_IS_TTY: 1

# clone_script:
#   - bash -lc "git clone -q --branch=$APPVEYOR_REPO_BRANCH https://github.com/${APPVEYOR_REPO_NAME}.git $APPVEYOR_BUILD_FOLDER"
#   - bash -lc "cd $APPVEYOR_BUILD_FOLDER && git checkout -qf $APPVEYOR_REPO_BRANCH"
#   - bash -lc "cd $APPVEYOR_BUILD_FOLDER && git submodule update --init --recursive"

install:
  # update mysy2
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S git"
  - C:\msys64\usr\bin\bash -lc "cat ~/.bashrc ~/.bash_profile"
  # - '"C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine'
  # - docker-switch-linux # Suggested way to do the exact same command above

# This is how you select "Script mode" instead of "MSBuild" mode. There MUST
# be something in build_script, else it doesn't count :(
build_script:
  - rem

test_script:
  # tests/optionaltest and tests/shtest fail on Windows; run them
  # anyways but ignore their failures.  Also, trace shtest.
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && source setup.env && just test"
  # - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && source setup.env && just test int_appveyor"
  # Appveyor only has Docker with linux containers in closed beta/"Premium" service :()
