version: "2.3"

services:
  docs:
    build:
      context: docs/docker
    image: ${DOCS_COMPILE_IMAGE-vsiri/sphinxdocs:compile}
    environment:
      - DOCKER_UID=${VSI_COMMON_UID-1000}
      - DOCKER_GIDS=${VSI_COMMON_GIDS-1000}
      - DOCKER_GROUP_NAMES=user
      - DOCKER_USERNAME=user
    volumes:
      - type: bind
        source: ${VSI_COMMON_DIR}
        target: /vsi
      - type: bind
        source: ${DOCS_SOURCE_DIR-}
        target: /src
      - type: bind
        source: ${DOCS_DIR-}
        target: /docs
