version: 2.1

# -----
# generic yaml anchors (reusable by multiple projects)
# -----
x-stuff:
  # container configuration & update
  container_config: &container_config
    working_directory: ~/repo
    shell: /bin/bash -eu
    docker:
      - image: vsiri/circleci:bash-compose-lfs

commands:
  submodule_checkout:
    description: Checks out submodules
    steps:
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --recursive --init
  dependencies_and_smuggle:
    description: Install dependencies and copies the source dir to the remote docker host
    steps:
      - run:
          name: Install test dependencies and smuggle vsi to host
          command: |
            apk add --no-cache perl jq
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            . setup.env
            tar c . | docker run -i --rm -v /root/repo:/src -w /src alpine:3.11 tar x

jobs:
  compile_docs:
    <<: *container_config

    steps:
      - checkout
      - submodule_checkout
      - setup_remote_docker
      - dependencies_and_smuggle

      - run:
          name: Generate docs
          command: |
            . setup.env
            tar c . | docker run -i --rm -v /root/repo:/src -w /src alpine:3.11 tar x
            SPHINXOPTS='-W  --keep-going' just sphinx build compile -n --all
            docker run --rm -v /root/repo:/src -w /src alpine:3.11 tar c ./docs/_build/html | tar x

      - persist_to_workspace:
          root: docs/_build
          paths: html

  run_bash_and_os_tests:
    <<: *container_config
    parallelism: 3
    steps:
      - checkout
      - submodule_checkout
      - setup_remote_docker
      - dependencies_and_smuggle
      - run:
          name: Run test on Bash Versions
          # Using CI load here was slower, so just pull image that are manually
          # pushed to dockerhub
          command: |
            # Load just stuff
            source setup.env
            source linux/just_files/just_env vsi_common.env
            # Docker login
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
            # Add two lists together
            tests=()
            for (( i=0; i<${#VSI_COMMON_BASH_TEST_VERSIONS[@]}; i++ ))
            {
              tests+=(bash_${VSI_COMMON_BASH_TEST_VERSIONS[i]})
            }
            for (( i=0; i<${#VSI_COMMON_TEST_OSES[@]}; i++ ))
            {
              tests+=(os_${VSI_COMMON_TEST_OSES[i]})
            }
            # Split by parallelism
            tests=($(IFS=$'\n'; echo "${tests[*]}" | circleci tests split))
            # Run tests
            for t in "${tests[@]}"; do \
              if [[ ${t} = os_* ]]; then
                just pull os "${t#os_}"
                just test os "${t#os_}" just test # -- test int
              elif [[ ${t} = bash_* ]]; then
                just pull bash "${t#bash_}"
                just test bash "${t#bash_}" all tests
              else
                echo "Something went wrong"
                exit 3
              fi
            done

  deploy_docs:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: /docs
      - run:
          name: Checkout gh-pages and update
          command: |
            # Load the functions new_just uses
            source ./linux/just_files/new_just

            git checkout gh-pages || git checkout --orphan gh-pages
            git reset --hard # This is important if gh-pages was just created
            git rm $(git ls-files)
            mv /docs/html/* ./
            touch .nojekyll

            # restore new_just file
            git show "origin/${CIRCLE_BRANCH}:linux/just_files/new_just" > ./new_just
            # patch the missing functions with copies from the sourced version above
            function_names=($(sed -nE 's|^ *function (.*)\(\)\{ :;}|\1|p' ./new_just))

            for function_name in "${function_names[@]}"; do
              declare -pf "${function_name}" | sed -i '/function '"${function_name}"'(){ :;}/{r /dev/stdin
                                                                                              d}' ./new_just
            done

            git add --all
            if [ "$(git status --porcelain -uno | wc -l)" != "0" ]; then
              git config --global user.email "circleci@cirleci.com" > /dev/null 2>&1
              git config --global user.name "CircleCI" > /dev/null 2>&1
              git commit -m "Autobuild documentation [ci skip]"
              git remote set-url origin "https://${GH_NAME}:${GH_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
              git push origin gh-pages
            fi

# -----
# CircleCI workflows
# -----
workflows:
  vsi_common:
    jobs:
      - run_bash_and_os_tests
      - compile_docs
      - deploy_docs:
          requires:
            - compile_docs
          filters:
            branches:
              only:
                - master
