version: '3.2'

services:
  vsi:
    image: vsiri/vsi_common
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
  robodoc: #Deprecated
    image: andyneff/robodoc:latest
    volumes:
      - "${SRC_DIR-.}:/src"
      - "${DOC_DIR-./docs}:/doc"
    command: ['--rc', '/src/robodoc.rc']
  sphinx:
    build:
      context: .
      dockerfile: sphinx.Dockerfile
    image: ${SPHINX_COMPILE_IMAGE-vsiri/sphinxdocs:compile}
    environment: &plugin_environment
      DOCKER_UID: ${VSI_COMMON_UID-1000}
      DOCKER_GIDS: ${VSI_COMMON_GIDS-1000}
      DOCKER_GROUP_NAMES: ${VSI_COMMON_GROUP_NAMES-user}
      DOCKER_USERNAME: user
      JUST_SETTINGS: ${VSI_COMMON_JUST_SETTINGS-}
    volumes:
      - &vsi_common_volume
        type: bind
        source: ${VSI_COMMON_DIR}
        target: /vsi
      - type: bind
        source: ${DOCS_SOURCE_DIR-}
        target: /src
      - type: bind
        source: ${DOCS_DIR-}
        target: /docs
  bashcov:
    build:
      context: .
      dockerfile: bashcov.Dockerfile
    image: ${BASHCOV_IMAGE-vsiri/bashcov:latest}
    environment:
      <<: *plugin_environment
      TESTLIB_PARALLEL:
      # DOCKER_HOST:
    volumes:
      - <<: *vsi_common_volume
      - type: bind
        source: ${BASH_COV_SOURCE_DIR-}
        target: /src
  makeself:
    build:
      context: .
      dockerfile: makeself.Dockerfile
      args:
        # 2.4.3 not released yet, using a master sha
        - MAKESELF_VERSION=${MAKESELF_VERSION-fe8e727e8955c0d10f48e318b28957fd0638464a}
    image: ${MAKESELF_IMAGE-vsiri/makeself:latest}
    environment:
      <<: *plugin_environment
      MAKESELF_NAME: just
      MAKESELF_LABEL: just_label
    volumes:
      - type: bind
        source: ${MAKESELF_SOURCE_DIR-}
        target: /src
      - type: bind
        source: ${MAKESELF_DIST_DIR-}
        target: /dist
    # platform: linux